server.port: 443

server.tomcat.max-threads: 16
server.tomcat.max-connections: 16

server.ssl.key-store-type: PKCS12
server.ssl.key-store: keystore.p12
server.ssl.key-alias: mt4ssl
server.ssl.key-store-password: ZAQ!xsw2cde3
server.ssl.socket.port: 523

spring.thymeleaf.cache: false
spring.thymeleaf.check-template: true
spring.thymeleaf.check-template-location: true
spring.thymeleaf.servlet.content-type: text/html
spring.thymeleaf.enabled: true
spring.thymeleaf.encoding: UTF-8
spring.thymeleaf.mode: HTML
spring.thymeleaf.prefix: classpath:/templates/
spring.thymeleaf.suffix: .html

spring.redis.hostName: localhost
spring.redis.database: 0
spring.redis.port: 6379
spring.redis.password: 
spring.redis.timeout: 200
spring.redis.lettuce.pool.max-active: 2
spring.redis.lettuce.pool.max-wait: 1
spring.redis.lettuce.pool.max-idle: 2
spring.redis.lettuce.pool.min-idle: 1

spring.cache.type: REDIS
spring.cache.redis.cache-null-values: false
spring.cache.redis.time-to-live: 20
spring.cache.redis.use-key-prefix: false

logging.file: my.log
